-- MySQL Script generated by MySQL Workbench
-- Mon Dec 29 10:25:38 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Admin`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Admin` (
  `admin_id` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`admin_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Class`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Class` (
  `class_id` VARCHAR(45) NOT NULL,
  `dept_id` VARCHAR(45) NOT NULL,
  `counselor_id` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`class_id`),
  CONSTRAINT `dept_id`
    FOREIGN KEY ()
    REFERENCES `mydb`.`Department` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Counselor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Counselor` (
  `counselor_id` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `dept_id` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`counselor_id`),
  CONSTRAINT `dept_id`
    FOREIGN KEY ()
    REFERENCES `mydb`.`Department` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Course`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Course` (
  `course_id` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `credits` INT NOT NULL,
  `capacity` INT NOT NULL,
  `teacher_id` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`course_id`),
  CONSTRAINT `teacher_id`
    FOREIGN KEY ()
    REFERENCES `mydb`.`Teacher` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Department`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Department` (
  `dept_id` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`dept_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Enrollment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Enrollment` (
  `enrollment_id` VARCHAR(45) NOT NULL,
  `student_id` VARCHAR(45) NOT NULL,
  `schedule_id` VARCHAR(45) NOT NULL,
  `score` INT NOT NULL,
  `status` VARCHAR(45) NULL,
  PRIMARY KEY (`enrollment_id`),
  CONSTRAINT `student_id`
    FOREIGN KEY ()
    REFERENCES `mydb`.`Student` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `schedule_id`
    FOREIGN KEY ()
    REFERENCES `mydb`.`Semester` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Semester`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Semester` (
  `schedule_id` VARCHAR(45) NOT NULL,
  `course_id` VARCHAR(45) NOT NULL,
  `semester_name` VARCHAR(45) NOT NULL,
  `time_slot` VARCHAR(45) NOT NULL,
  `classroom` VARCHAR(45) NULL,
  PRIMARY KEY (`schedule_id`),
  CONSTRAINT `course_id`
    FOREIGN KEY ()
    REFERENCES `mydb`.`Course` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Student` (
  `student_id` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `class_id` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`student_id`),
  CONSTRAINT `class_id`
    FOREIGN KEY ()
    REFERENCES `mydb`.`Class` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Teacher`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Teacher` (
  `teacher_id` VARCHAR(45) NOT NULL,
  `name` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `dept_id` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`teacher_id`),
  CONSTRAINT `dept_id`
    FOREIGN KEY ()
    REFERENCES `mydb`.`Department` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
